spring.datasource.url=jdbc:postgresql://localhost:5432/prepgenie
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Google Gemini API Key
openrouter.api.key=${OPENROUTER_API_KEY}
